runtime: python39
entrypoint: gunicorn -w 4 -b :$PORT app:app

handlers:
- url: /.*
  script: auto

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
